accounts/urls.py
from django.urls import path
from. import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SighUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('post/new/', views.BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', views.BlogDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/edit/', views.BlogUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', views.BlogDeleteView.as_view(), name='post_delete'),
    path('', views.BlogListView.as_view(), name='home'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('blog.urls', namespace='blog')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('', views.HomePageView.as_view(), name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={
            "pk": self.pk
        })

pages/models.py
from django.db import models


class Post(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:50]

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView

class SighUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name ='registration/sighup.html'

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy


class BlogListView(ListView):
    model = models.Post
    template_name = 'blog/home.html'


class BlogDetailView(DetailView):
    model = models.Post
    template_name = 'blog/post_detail.html'


class BlogCreateView(CreateView):
    model = models.Post
    template_name = 'blog/post_new.html'
    fields = ['title', 'author', 'body', ]


class BlogUpdateView(UpdateView):
    model = models.Post
    template_name = 'blog/post_edit.html'
    fields = ['title', 'body', ]


class BlogDeleteView(DeleteView):
    model = models.Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy("blog:home")

pages/views.py
from django.views.generic import ListView, TemplateView
from . import models

class HomePageView(ListView):
    model = models.Post
    template_name = 'pages/home.html'

class AboutPageView(TemplateView):
    template_name = 'pages/about.html'

templates/base.html
{% load static %}
<html>
<head>
    <title>Django blog</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
</head>
<body>
<div>
    <header>
        <div class="nav-left">
            <h1><a href="{% url 'blog:home' %}">Django blog</a></h1>
        </div>
        <div class="nav-right">
            <h1><a href="{% url 'blog:post_new' %}">New Blog Post</a></h1>
        </div>
    </header>
    {% if user.is_authenticated %}
        <p>Hi {{ user.username }}</p>
        <a href="{% url 'logout' %}">Log out</a>
    {% else %}
        <p>You are not logged in.</p>
        <a href="{% url "login" %}">Log In</a> |
        <a href="{% url 'accounts:signup' %}">Sign Up</a>
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/blog/home.html
{% extends "base.html" %}

{% block content %}
    {% for post in post_list %}
        <div class="post-entry">
            <h2><a href="{% url "blog:post_detail" post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.body|truncatechars:15 }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/blog/post_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete post</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ post.title }}</p>
        <input type="submit" value="Delete">
    </form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="post-entry">
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
    </div>
    <a href="{% url 'blog:post_edit' post.pk %}">+ Edit Blog Post</a>
    <a href="{% url 'blog:post_delete' post.pk %}">+ Delete Blog Post</a>
{% endblock %}

templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    </form>
{% endblock %}

templates/blog/post_new.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

templates/pages/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About page</h1>
{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Message board homepage</h1>
    <ul>
        {% for post in post_list %}
            <li>{{ post.text }}</li>
        {% endfor %}
    </ul>
{% endblock %}